name: nightly

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run
        run: npm run start
        env:
          LSC_TOKEN: ${{ secrets.LSC_TOKEN }}
